### PR TITLE
Improved Userlist

### PR DESCRIPTION
**Pull request by KenavR**
Hi,

I added a search function to the user list, reduced the offline users to the last 10 online - including a more button. I also added an indicator for users online/found users. This should address issues #30 and #32.

### How it looks
users

I tested it with a very limited amount of users, that's why in the screenshot the `more` button appears after only one entry. Mods and Online users are ordered alphabetical, offline users by the last time they were online.

### CODE REVIEW

**Comment by megamattron** [comment]
Looking really cool @KenavR - I merged it in. I also made a slight improvement for when guest users are present in the room. It's an edge case but occasionally happens. Deploying now!

**Comment by KenavR** [comment]
I don't know if your changes are the reason, but I think it has definitely has something to do with guest users, the "more" button, should disappear when there are no more users (and after you searched for something) but it is always present.  

If [that's](https://github.com/larvalabs/breaker/blob/master/web/userlist/UserListItems.jsx#L87) the thing you changed, then the problem is [this](https://github.com/larvalabs/breaker/blob/master/web/userlist/UserListItems.jsx#L52) line. I could look into it, but does every guest gets a unique name? guest1...X? if so the line should be changed to 

```
 return this.getOrderedList(props)
      .filter((user) => user.get('username').toLowerCase().indexOf(filterBy) > -1 && !user.get('username').startsWith('guest'));
```

This potentially creates an issue if there is a legitimately user in the channel which starts wit "guest".

**Comment by megamattron** [comment]
There is only 1 guest user, we just open multiple connections for that single user. The change that I made is in c0ab671but basically it involves using this.state.filteredUserCount instead of just the items array size. The filtered list has the guest user already removed. And to test in development with a guest user present, just open the chat room in an incognito window.

Does that help? Let me know if you need me to look into anything.

**Comment by megamattron** [comment]
Hey @KenavR I think I realized my mistake. I was using the filtered count and list in inappropriate places. I also realized that it doesn't make sense to be doing the guest user filtering everywhere, I should just do it in the user list selectors once and then no one else has to worry about it. So that's what ef304c4 does. Deploying now and will see if that does the trick.

**Comment by megamattron** [comment]
Ok, and with that last commit I think I fixed the more link bug finally. Check it out when you get a chance. I'm not the best at React by any stretch so I could be making some mistakes.

**Pull request merged**
